package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admindetail generated by hbm2java
 */
@Entity
@Table(name = "admindetail", catalog = "ccwchina")
public class Admindetail implements java.io.Serializable {

	private String adminId;
	private String password;
	private String adminName;
	private String email;
	private String flag;
	private String avaliable;

	public Admindetail() {
	}

	public Admindetail(String adminId) {
		this.adminId = adminId;
	}

	public Admindetail(String adminId, String password, String adminName,
			String email, String flag, String avaliable) {
		this.adminId = adminId;
		this.password = password;
		this.adminName = adminName;
		this.email = email;
		this.flag = flag;
		this.avaliable = avaliable;
	}

	@Id
	@Column(name = "adminId", unique = true, nullable = false, length = 45)
	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "adminName", length = 45)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

}
