package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Advertisement generated by hbm2java
 */
@Entity
@Table(name = "advertisement", catalog = "ccwchina")
public class Advertisement implements java.io.Serializable {

	private Long advertisementId;
	private String advertisementPath;
	private String advertisementTitle;
	private String advertisementDesc;
	private String flag;
	private String avaliable;
	private String advertisementLink;

	public Advertisement() {
	}

	public Advertisement(String advertisementPath, String advertisementTitle,
			String advertisementDesc, String flag, String avaliable,
			String advertisementLink) {
		this.advertisementPath = advertisementPath;
		this.advertisementTitle = advertisementTitle;
		this.advertisementDesc = advertisementDesc;
		this.flag = flag;
		this.avaliable = avaliable;
		this.advertisementLink = advertisementLink;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "advertisementId", unique = true, nullable = false)
	public Long getAdvertisementId() {
		return this.advertisementId;
	}

	public void setAdvertisementId(Long advertisementId) {
		this.advertisementId = advertisementId;
	}

	@Column(name = "advertisementPath", length = 65535)
	public String getAdvertisementPath() {
		return this.advertisementPath;
	}

	public void setAdvertisementPath(String advertisementPath) {
		this.advertisementPath = advertisementPath;
	}

	@Column(name = "advertisementTitle", length = 45)
	public String getAdvertisementTitle() {
		return this.advertisementTitle;
	}

	public void setAdvertisementTitle(String advertisementTitle) {
		this.advertisementTitle = advertisementTitle;
	}

	@Column(name = "advertisementDesc", length = 200)
	public String getAdvertisementDesc() {
		return this.advertisementDesc;
	}

	public void setAdvertisementDesc(String advertisementDesc) {
		this.advertisementDesc = advertisementDesc;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@Column(name = "advertisementLink", length = 65535)
	public String getAdvertisementLink() {
		return this.advertisementLink;
	}

	public void setAdvertisementLink(String advertisementLink) {
		this.advertisementLink = advertisementLink;
	}

}
