package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Classtime generated by hbm2java
 */
@Entity
@Table(name = "classtime", catalog = "ccwchina", uniqueConstraints = @UniqueConstraint(columnNames = "order"))
public class Classtime implements java.io.Serializable {

	private Integer classTimeId;
	private String classTimeContent;
	private String flag;
	private String avaliable;
	private Integer order;
	private Set<Coursecalendar> coursecalendars = new HashSet<Coursecalendar>(0);
	private Set<Orderprivate> orderprivates = new HashSet<Orderprivate>(0);

	public Classtime() {
	}

	public Classtime(String classTimeContent, String flag, String avaliable,
			Integer order, Set<Coursecalendar> coursecalendars,
			Set<Orderprivate> orderprivates) {
		this.classTimeContent = classTimeContent;
		this.flag = flag;
		this.avaliable = avaliable;
		this.order = order;
		this.coursecalendars = coursecalendars;
		this.orderprivates = orderprivates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "classTimeId", unique = true, nullable = false)
	public Integer getClassTimeId() {
		return this.classTimeId;
	}

	public void setClassTimeId(Integer classTimeId) {
		this.classTimeId = classTimeId;
	}

	@Column(name = "classTimeContent", length = 100)
	public String getClassTimeContent() {
		return this.classTimeContent;
	}

	public void setClassTimeContent(String classTimeContent) {
		this.classTimeContent = classTimeContent;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@Column(name = "order", unique = true)
	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "classtime")
	public Set<Coursecalendar> getCoursecalendars() {
		return this.coursecalendars;
	}

	public void setCoursecalendars(Set<Coursecalendar> coursecalendars) {
		this.coursecalendars = coursecalendars;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "classtime")
	public Set<Orderprivate> getOrderprivates() {
		return this.orderprivates;
	}

	public void setOrderprivates(Set<Orderprivate> orderprivates) {
		this.orderprivates = orderprivates;
	}

}
