package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Confirmtime generated by hbm2java
 */
@Entity
@Table(name = "confirmtime", catalog = "ccwchina")
public class Confirmtime implements java.io.Serializable {

	private Integer confirmTimeId;
	private String confirmTimeContent;
	private String flag;
	private String avaliable;
	private Set<Orderbasic> orderbasics = new HashSet<Orderbasic>(0);

	public Confirmtime() {
	}

	public Confirmtime(String confirmTimeContent, String flag,
			String avaliable, Set<Orderbasic> orderbasics) {
		this.confirmTimeContent = confirmTimeContent;
		this.flag = flag;
		this.avaliable = avaliable;
		this.orderbasics = orderbasics;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "confirmTimeId", unique = true, nullable = false)
	public Integer getConfirmTimeId() {
		return this.confirmTimeId;
	}

	public void setConfirmTimeId(Integer confirmTimeId) {
		this.confirmTimeId = confirmTimeId;
	}

	@Column(name = "confirmTimeContent", length = 45)
	public String getConfirmTimeContent() {
		return this.confirmTimeContent;
	}

	public void setConfirmTimeContent(String confirmTimeContent) {
		this.confirmTimeContent = confirmTimeContent;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "confirmtime")
	public Set<Orderbasic> getOrderbasics() {
		return this.orderbasics;
	}

	public void setOrderbasics(Set<Orderbasic> orderbasics) {
		this.orderbasics = orderbasics;
	}

}
