package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coursepackage generated by hbm2java
 */
@Entity
@Table(name = "coursepackage", catalog = "ccwchina")
public class Coursepackage implements java.io.Serializable {

	private String coursePackageId;
	private Coursetrunktype coursetrunktype;
	private String flag;
	private String avaliable;
	private Set<Orderprivate> orderprivates = new HashSet<Orderprivate>(0);
	private Set<Packagewithcourse> packagewithcourses = new HashSet<Packagewithcourse>(
			0);

	public Coursepackage() {
	}

	public Coursepackage(String coursePackageId) {
		this.coursePackageId = coursePackageId;
	}

	public Coursepackage(String coursePackageId,
			Coursetrunktype coursetrunktype, String flag, String avaliable,
			Set<Orderprivate> orderprivates,
			Set<Packagewithcourse> packagewithcourses) {
		this.coursePackageId = coursePackageId;
		this.coursetrunktype = coursetrunktype;
		this.flag = flag;
		this.avaliable = avaliable;
		this.orderprivates = orderprivates;
		this.packagewithcourses = packagewithcourses;
	}

	@Id
	@Column(name = "coursePackageId", unique = true, nullable = false, length = 45)
	public String getCoursePackageId() {
		return this.coursePackageId;
	}

	public void setCoursePackageId(String coursePackageId) {
		this.coursePackageId = coursePackageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseTrunkTypeId")
	public Coursetrunktype getCoursetrunktype() {
		return this.coursetrunktype;
	}

	public void setCoursetrunktype(Coursetrunktype coursetrunktype) {
		this.coursetrunktype = coursetrunktype;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "coursepackage")
	public Set<Orderprivate> getOrderprivates() {
		return this.orderprivates;
	}

	public void setOrderprivates(Set<Orderprivate> orderprivates) {
		this.orderprivates = orderprivates;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "coursepackage")
	public Set<Packagewithcourse> getPackagewithcourses() {
		return this.packagewithcourses;
	}

	public void setPackagewithcourses(Set<Packagewithcourse> packagewithcourses) {
		this.packagewithcourses = packagewithcourses;
	}

}
