package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Courselocation generated by hbm2java
 */
@Entity
@Table(name = "courselocation", catalog = "ccwchina")
public class Courselocation implements java.io.Serializable {

	private Integer courseLocationId;
	private String courseLocationName;
	private String flag;
	private String avaliable;
	private Set<Userdetail> userdetails = new HashSet<Userdetail>(0);
	private Set<Orderprivate> orderprivates = new HashSet<Orderprivate>(0);
	private Set<Coursecalendar> coursecalendars = new HashSet<Coursecalendar>(0);

	public Courselocation() {
	}

	public Courselocation(String courseLocationName, String flag,
			String avaliable, Set<Userdetail> userdetails,
			Set<Orderprivate> orderprivates, Set<Coursecalendar> coursecalendars) {
		this.courseLocationName = courseLocationName;
		this.flag = flag;
		this.avaliable = avaliable;
		this.userdetails = userdetails;
		this.orderprivates = orderprivates;
		this.coursecalendars = coursecalendars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "courseLocationId", unique = true, nullable = false)
	public Integer getCourseLocationId() {
		return this.courseLocationId;
	}

	public void setCourseLocationId(Integer courseLocationId) {
		this.courseLocationId = courseLocationId;
	}

	@Column(name = "courseLocationName", length = 45)
	public String getCourseLocationName() {
		return this.courseLocationName;
	}

	public void setCourseLocationName(String courseLocationName) {
		this.courseLocationName = courseLocationName;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "courselocation")
	public Set<Userdetail> getUserdetails() {
		return this.userdetails;
	}

	public void setUserdetails(Set<Userdetail> userdetails) {
		this.userdetails = userdetails;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "courselocation")
	public Set<Orderprivate> getOrderprivates() {
		return this.orderprivates;
	}

	public void setOrderprivates(Set<Orderprivate> orderprivates) {
		this.orderprivates = orderprivates;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "courselocation")
	public Set<Coursecalendar> getCoursecalendars() {
		return this.coursecalendars;
	}

	public void setCoursecalendars(Set<Coursecalendar> coursecalendars) {
		this.coursecalendars = coursecalendars;
	}

}
