package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "ccwchina")
public class Course implements java.io.Serializable {

	private String courseId;
	private Coursebranchtype coursebranchtype;
	private Coursetrunktype coursetrunktype;
	private String pictureOne;
	private String pictureTwo;
	private String pictureThree;
	private String pictureFour;
	private String flag;
	private String avaliable;
	private String courseNameEn;
	private String courseNameCn;
	private String courseNameJp;
	private String courseDescriptionEn;
	private String courseDescriptionCn;
	private String courseDescriptionJp;
	private String searchKeyWords;
	private String searchDescription;
	private Set<Packagewithcourse> packagewithcourses = new HashSet<Packagewithcourse>(
			0);
	private Set<Calendarwithcourse> calendarwithcourses = new HashSet<Calendarwithcourse>(
			0);

	public Course() {
	}

	public Course(String courseId) {
		this.courseId = courseId;
	}

	public Course(String courseId, Coursebranchtype coursebranchtype,
			Coursetrunktype coursetrunktype, String pictureOne,
			String pictureTwo, String pictureThree, String pictureFour,
			String flag, String avaliable, String courseNameEn,
			String courseNameCn, String courseNameJp,
			String courseDescriptionEn, String courseDescriptionCn,
			String courseDescriptionJp, String searchKeyWords,
			String searchDescription,
			Set<Packagewithcourse> packagewithcourses,
			Set<Calendarwithcourse> calendarwithcourses) {
		this.courseId = courseId;
		this.coursebranchtype = coursebranchtype;
		this.coursetrunktype = coursetrunktype;
		this.pictureOne = pictureOne;
		this.pictureTwo = pictureTwo;
		this.pictureThree = pictureThree;
		this.pictureFour = pictureFour;
		this.flag = flag;
		this.avaliable = avaliable;
		this.courseNameEn = courseNameEn;
		this.courseNameCn = courseNameCn;
		this.courseNameJp = courseNameJp;
		this.courseDescriptionEn = courseDescriptionEn;
		this.courseDescriptionCn = courseDescriptionCn;
		this.courseDescriptionJp = courseDescriptionJp;
		this.searchKeyWords = searchKeyWords;
		this.searchDescription = searchDescription;
		this.packagewithcourses = packagewithcourses;
		this.calendarwithcourses = calendarwithcourses;
	}

	@Id
	@Column(name = "courseId", unique = true, nullable = false, length = 45)
	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseBranchTypeId")
	public Coursebranchtype getCoursebranchtype() {
		return this.coursebranchtype;
	}

	public void setCoursebranchtype(Coursebranchtype coursebranchtype) {
		this.coursebranchtype = coursebranchtype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseTrunkTypeId")
	public Coursetrunktype getCoursetrunktype() {
		return this.coursetrunktype;
	}

	public void setCoursetrunktype(Coursetrunktype coursetrunktype) {
		this.coursetrunktype = coursetrunktype;
	}

	@Column(name = "pictureOne", length = 65535)
	public String getPictureOne() {
		return this.pictureOne;
	}

	public void setPictureOne(String pictureOne) {
		this.pictureOne = pictureOne;
	}

	@Column(name = "pictureTwo", length = 65535)
	public String getPictureTwo() {
		return this.pictureTwo;
	}

	public void setPictureTwo(String pictureTwo) {
		this.pictureTwo = pictureTwo;
	}

	@Column(name = "pictureThree", length = 65535)
	public String getPictureThree() {
		return this.pictureThree;
	}

	public void setPictureThree(String pictureThree) {
		this.pictureThree = pictureThree;
	}

	@Column(name = "pictureFour", length = 65535)
	public String getPictureFour() {
		return this.pictureFour;
	}

	public void setPictureFour(String pictureFour) {
		this.pictureFour = pictureFour;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@Column(name = "courseNameEn", length = 100)
	public String getCourseNameEn() {
		return this.courseNameEn;
	}

	public void setCourseNameEn(String courseNameEn) {
		this.courseNameEn = courseNameEn;
	}

	@Column(name = "courseNameCn", length = 100)
	public String getCourseNameCn() {
		return this.courseNameCn;
	}

	public void setCourseNameCn(String courseNameCn) {
		this.courseNameCn = courseNameCn;
	}

	@Column(name = "courseNameJp", length = 100)
	public String getCourseNameJp() {
		return this.courseNameJp;
	}

	public void setCourseNameJp(String courseNameJp) {
		this.courseNameJp = courseNameJp;
	}

	@Column(name = "courseDescriptionEn", length = 65535)
	public String getCourseDescriptionEn() {
		return this.courseDescriptionEn;
	}

	public void setCourseDescriptionEn(String courseDescriptionEn) {
		this.courseDescriptionEn = courseDescriptionEn;
	}

	@Column(name = "courseDescriptionCn", length = 65535)
	public String getCourseDescriptionCn() {
		return this.courseDescriptionCn;
	}

	public void setCourseDescriptionCn(String courseDescriptionCn) {
		this.courseDescriptionCn = courseDescriptionCn;
	}

	@Column(name = "courseDescriptionJp", length = 65535)
	public String getCourseDescriptionJp() {
		return this.courseDescriptionJp;
	}

	public void setCourseDescriptionJp(String courseDescriptionJp) {
		this.courseDescriptionJp = courseDescriptionJp;
	}

	@Column(name = "searchKeyWords", length = 100)
	public String getSearchKeyWords() {
		return this.searchKeyWords;
	}

	public void setSearchKeyWords(String searchKeyWords) {
		this.searchKeyWords = searchKeyWords;
	}

	@Column(name = "searchDescription", length = 65535)
	public String getSearchDescription() {
		return this.searchDescription;
	}

	public void setSearchDescription(String searchDescription) {
		this.searchDescription = searchDescription;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Packagewithcourse> getPackagewithcourses() {
		return this.packagewithcourses;
	}

	public void setPackagewithcourses(Set<Packagewithcourse> packagewithcourses) {
		this.packagewithcourses = packagewithcourses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Calendarwithcourse> getCalendarwithcourses() {
		return this.calendarwithcourses;
	}

	public void setCalendarwithcourses(
			Set<Calendarwithcourse> calendarwithcourses) {
		this.calendarwithcourses = calendarwithcourses;
	}

}
