package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Infomaillist generated by hbm2java
 */
@Entity
@Table(name = "infomaillist", catalog = "ccwchina")
public class Infomaillist implements java.io.Serializable {

	private Long mailId;
	private String firstname;
	private String lastname;
	private String email;
	private String flag;
	private String avaliable;
	private Date jointime;

	public Infomaillist() {
	}

	public Infomaillist(String firstname, String lastname, String email,
			String flag, String avaliable, Date jointime) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.flag = flag;
		this.avaliable = avaliable;
		this.jointime = jointime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mailId", unique = true, nullable = false)
	public Long getMailId() {
		return this.mailId;
	}

	public void setMailId(Long mailId) {
		this.mailId = mailId;
	}

	@Column(name = "firstname", length = 100)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 100)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 65535)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "jointime", length = 19)
	public Date getJointime() {
		return this.jointime;
	}

	public void setJointime(Date jointime) {
		this.jointime = jointime;
	}

}
