package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "ccwchina")
public class Item implements java.io.Serializable {

	private String itemId;
	private Itemtrunktype itemtrunktype;
	private String itemNameEn;
	private String itemNameCn;
	private String itemNameJp;
	private String itemDescriptionEn;
	private String itemDescriptionCn;
	private String itemDescriptionJp;
	private String searchKeyWords;
	private String searchDescription;
	private String pictureOne;
	private String pictureTwo;
	private String pictureThree;
	private String pictureFour;
	private String flag;
	private String avaliable;
	private Integer price;
	private Date startTime;
	private Date endTime;
	private Integer saledNumber;
	private Set<Orderitem> orderitems = new HashSet<Orderitem>(0);

	public Item() {
	}

	public Item(String itemId) {
		this.itemId = itemId;
	}

	public Item(String itemId, Itemtrunktype itemtrunktype, String itemNameEn,
			String itemNameCn, String itemNameJp, String itemDescriptionEn,
			String itemDescriptionCn, String itemDescriptionJp,
			String searchKeyWords, String searchDescription, String pictureOne,
			String pictureTwo, String pictureThree, String pictureFour,
			String flag, String avaliable, Integer price, Date startTime,
			Date endTime, Integer saledNumber, Set<Orderitem> orderitems) {
		this.itemId = itemId;
		this.itemtrunktype = itemtrunktype;
		this.itemNameEn = itemNameEn;
		this.itemNameCn = itemNameCn;
		this.itemNameJp = itemNameJp;
		this.itemDescriptionEn = itemDescriptionEn;
		this.itemDescriptionCn = itemDescriptionCn;
		this.itemDescriptionJp = itemDescriptionJp;
		this.searchKeyWords = searchKeyWords;
		this.searchDescription = searchDescription;
		this.pictureOne = pictureOne;
		this.pictureTwo = pictureTwo;
		this.pictureThree = pictureThree;
		this.pictureFour = pictureFour;
		this.flag = flag;
		this.avaliable = avaliable;
		this.price = price;
		this.startTime = startTime;
		this.endTime = endTime;
		this.saledNumber = saledNumber;
		this.orderitems = orderitems;
	}

	@Id
	@Column(name = "itemId", unique = true, nullable = false, length = 45)
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemTrunkTypeId")
	public Itemtrunktype getItemtrunktype() {
		return this.itemtrunktype;
	}

	public void setItemtrunktype(Itemtrunktype itemtrunktype) {
		this.itemtrunktype = itemtrunktype;
	}

	@Column(name = "itemNameEn", length = 65535)
	public String getItemNameEn() {
		return this.itemNameEn;
	}

	public void setItemNameEn(String itemNameEn) {
		this.itemNameEn = itemNameEn;
	}

	@Column(name = "itemNameCn", length = 65535)
	public String getItemNameCn() {
		return this.itemNameCn;
	}

	public void setItemNameCn(String itemNameCn) {
		this.itemNameCn = itemNameCn;
	}

	@Column(name = "itemNameJp", length = 65535)
	public String getItemNameJp() {
		return this.itemNameJp;
	}

	public void setItemNameJp(String itemNameJp) {
		this.itemNameJp = itemNameJp;
	}

	@Column(name = "itemDescriptionEn", length = 65535)
	public String getItemDescriptionEn() {
		return this.itemDescriptionEn;
	}

	public void setItemDescriptionEn(String itemDescriptionEn) {
		this.itemDescriptionEn = itemDescriptionEn;
	}

	@Column(name = "itemDescriptionCn", length = 65535)
	public String getItemDescriptionCn() {
		return this.itemDescriptionCn;
	}

	public void setItemDescriptionCn(String itemDescriptionCn) {
		this.itemDescriptionCn = itemDescriptionCn;
	}

	@Column(name = "itemDescriptionJp", length = 65535)
	public String getItemDescriptionJp() {
		return this.itemDescriptionJp;
	}

	public void setItemDescriptionJp(String itemDescriptionJp) {
		this.itemDescriptionJp = itemDescriptionJp;
	}

	@Column(name = "searchKeyWords", length = 65535)
	public String getSearchKeyWords() {
		return this.searchKeyWords;
	}

	public void setSearchKeyWords(String searchKeyWords) {
		this.searchKeyWords = searchKeyWords;
	}

	@Column(name = "searchDescription", length = 65535)
	public String getSearchDescription() {
		return this.searchDescription;
	}

	public void setSearchDescription(String searchDescription) {
		this.searchDescription = searchDescription;
	}

	@Column(name = "pictureOne", length = 65535)
	public String getPictureOne() {
		return this.pictureOne;
	}

	public void setPictureOne(String pictureOne) {
		this.pictureOne = pictureOne;
	}

	@Column(name = "pictureTwo", length = 65535)
	public String getPictureTwo() {
		return this.pictureTwo;
	}

	public void setPictureTwo(String pictureTwo) {
		this.pictureTwo = pictureTwo;
	}

	@Column(name = "pictureThree", length = 65535)
	public String getPictureThree() {
		return this.pictureThree;
	}

	public void setPictureThree(String pictureThree) {
		this.pictureThree = pictureThree;
	}

	@Column(name = "pictureFour", length = 65535)
	public String getPictureFour() {
		return this.pictureFour;
	}

	public void setPictureFour(String pictureFour) {
		this.pictureFour = pictureFour;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startTime", length = 10)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endTime", length = 10)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "saledNumber")
	public Integer getSaledNumber() {
		return this.saledNumber;
	}

	public void setSaledNumber(Integer saledNumber) {
		this.saledNumber = saledNumber;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "item")
	public Set<Orderitem> getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set<Orderitem> orderitems) {
		this.orderitems = orderitems;
	}

}
