package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Itemtrunktype generated by hbm2java
 */
@Entity
@Table(name = "itemtrunktype", catalog = "ccwchina", uniqueConstraints = @UniqueConstraint(columnNames = "itemTrunkTypePath"))
public class Itemtrunktype implements java.io.Serializable {

	private Integer itemTrunkTypeId;
	private String itemTrunkTypeNameKey;
	private String itemTrunkTypePath;
	private String flag;
	private String avaliable;
	private Set<Item> items = new HashSet<Item>(0);

	public Itemtrunktype() {
	}

	public Itemtrunktype(String itemTrunkTypeNameKey, String itemTrunkTypePath,
			String flag, String avaliable, Set<Item> items) {
		this.itemTrunkTypeNameKey = itemTrunkTypeNameKey;
		this.itemTrunkTypePath = itemTrunkTypePath;
		this.flag = flag;
		this.avaliable = avaliable;
		this.items = items;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "itemTrunkTypeId", unique = true, nullable = false)
	public Integer getItemTrunkTypeId() {
		return this.itemTrunkTypeId;
	}

	public void setItemTrunkTypeId(Integer itemTrunkTypeId) {
		this.itemTrunkTypeId = itemTrunkTypeId;
	}

	@Column(name = "itemTrunkTypeNameKey", length = 100)
	public String getItemTrunkTypeNameKey() {
		return this.itemTrunkTypeNameKey;
	}

	public void setItemTrunkTypeNameKey(String itemTrunkTypeNameKey) {
		this.itemTrunkTypeNameKey = itemTrunkTypeNameKey;
	}

	@Column(name = "itemTrunkTypePath", unique = true, length = 45)
	public String getItemTrunkTypePath() {
		return this.itemTrunkTypePath;
	}

	public void setItemTrunkTypePath(String itemTrunkTypePath) {
		this.itemTrunkTypePath = itemTrunkTypePath;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "itemtrunktype")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
