package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orderitem generated by hbm2java
 */
@Entity
@Table(name = "orderitem", catalog = "ccwchina")
public class Orderitem implements java.io.Serializable {

	private String orderItemId;
	private Orderstatus orderstatus;
	private Userdetail userdetail;
	private Item item;
	private String contactPerson;
	private String email;
	private String cellphone;
	private Date bookingTime;
	private Date checkTime;
	private Integer points;
	private String flag;
	private String avaliable;

	public Orderitem() {
	}

	public Orderitem(String orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Orderitem(String orderItemId, Orderstatus orderstatus,
			Userdetail userdetail, Item item, String contactPerson,
			String email, String cellphone, Date bookingTime, Date checkTime,
			Integer points, String flag, String avaliable) {
		this.orderItemId = orderItemId;
		this.orderstatus = orderstatus;
		this.userdetail = userdetail;
		this.item = item;
		this.contactPerson = contactPerson;
		this.email = email;
		this.cellphone = cellphone;
		this.bookingTime = bookingTime;
		this.checkTime = checkTime;
		this.points = points;
		this.flag = flag;
		this.avaliable = avaliable;
	}

	@Id
	@Column(name = "orderItemId", unique = true, nullable = false, length = 45)
	public String getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(String orderItemId) {
		this.orderItemId = orderItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderStatusId")
	public Orderstatus getOrderstatus() {
		return this.orderstatus;
	}

	public void setOrderstatus(Orderstatus orderstatus) {
		this.orderstatus = orderstatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public Userdetail getUserdetail() {
		return this.userdetail;
	}

	public void setUserdetail(Userdetail userdetail) {
		this.userdetail = userdetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemId")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "contactPerson", length = 100)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "cellphone", length = 100)
	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bookingTime", length = 19)
	public Date getBookingTime() {
		return this.bookingTime;
	}

	public void setBookingTime(Date bookingTime) {
		this.bookingTime = bookingTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checkTime", length = 19)
	public Date getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	@Column(name = "points")
	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

}
