package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Orderstatus generated by hbm2java
 */
@Entity
@Table(name = "orderstatus", catalog = "ccwchina")
public class Orderstatus implements java.io.Serializable {

	private Integer orderStatusId;
	private String orderStatusName;
	private String flag;
	private String avaliable;
	private Set<Orderbasic> orderbasics = new HashSet<Orderbasic>(0);
	private Set<Orderitem> orderitems = new HashSet<Orderitem>(0);

	public Orderstatus() {
	}

	public Orderstatus(String orderStatusName, String flag, String avaliable,
			Set<Orderbasic> orderbasics, Set<Orderitem> orderitems) {
		this.orderStatusName = orderStatusName;
		this.flag = flag;
		this.avaliable = avaliable;
		this.orderbasics = orderbasics;
		this.orderitems = orderitems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orderStatusId", unique = true, nullable = false)
	public Integer getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Integer orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "orderStatusName", length = 45)
	public String getOrderStatusName() {
		return this.orderStatusName;
	}

	public void setOrderStatusName(String orderStatusName) {
		this.orderStatusName = orderStatusName;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "orderstatus")
	public Set<Orderbasic> getOrderbasics() {
		return this.orderbasics;
	}

	public void setOrderbasics(Set<Orderbasic> orderbasics) {
		this.orderbasics = orderbasics;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "orderstatus")
	public Set<Orderitem> getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set<Orderitem> orderitems) {
		this.orderitems = orderitems;
	}

}
