package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Orderpublic generated by hbm2java
 */
@Entity
@Table(name = "orderpublic", catalog = "ccwchina", uniqueConstraints = @UniqueConstraint(columnNames = "orderBasicId"))
public class Orderpublic implements java.io.Serializable {

	private String orderPublicId;
	private Orderbasic orderbasic;
	private Coursecalendar coursecalendar;
	private Integer totalPeopleNumber;
	private String needMap;
	private String flag;
	private String avaliable;
	private Integer totalPrice;

	public Orderpublic() {
	}

	public Orderpublic(String orderPublicId, Orderbasic orderbasic) {
		this.orderPublicId = orderPublicId;
		this.orderbasic = orderbasic;
	}

	public Orderpublic(String orderPublicId, Orderbasic orderbasic,
			Coursecalendar coursecalendar, Integer totalPeopleNumber,
			String needMap, String flag, String avaliable, Integer totalPrice) {
		this.orderPublicId = orderPublicId;
		this.orderbasic = orderbasic;
		this.coursecalendar = coursecalendar;
		this.totalPeopleNumber = totalPeopleNumber;
		this.needMap = needMap;
		this.flag = flag;
		this.avaliable = avaliable;
		this.totalPrice = totalPrice;
	}

	@Id
	@Column(name = "orderPublicId", unique = true, nullable = false, length = 45)
	public String getOrderPublicId() {
		return this.orderPublicId;
	}

	public void setOrderPublicId(String orderPublicId) {
		this.orderPublicId = orderPublicId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderBasicId", unique = true, nullable = false)
	public Orderbasic getOrderbasic() {
		return this.orderbasic;
	}

	public void setOrderbasic(Orderbasic orderbasic) {
		this.orderbasic = orderbasic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseCalendarId")
	public Coursecalendar getCoursecalendar() {
		return this.coursecalendar;
	}

	public void setCoursecalendar(Coursecalendar coursecalendar) {
		this.coursecalendar = coursecalendar;
	}

	@Column(name = "totalPeopleNumber")
	public Integer getTotalPeopleNumber() {
		return this.totalPeopleNumber;
	}

	public void setTotalPeopleNumber(Integer totalPeopleNumber) {
		this.totalPeopleNumber = totalPeopleNumber;
	}

	@Column(name = "needMap", length = 45)
	public String getNeedMap() {
		return this.needMap;
	}

	public void setNeedMap(String needMap) {
		this.needMap = needMap;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@Column(name = "totalPrice")
	public Integer getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Integer totalPrice) {
		this.totalPrice = totalPrice;
	}

}
