package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Packagewithcourse generated by hbm2java
 */
@Entity
@Table(name = "packagewithcourse", catalog = "ccwchina")
public class Packagewithcourse implements java.io.Serializable {

	private Long packageWithCourseId;
	private Course course;
	private Coursepackage coursepackage;

	public Packagewithcourse() {
	}

	public Packagewithcourse(Course course, Coursepackage coursepackage) {
		this.course = course;
		this.coursepackage = coursepackage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "packageWithCourseId", unique = true, nullable = false)
	public Long getPackageWithCourseId() {
		return this.packageWithCourseId;
	}

	public void setPackageWithCourseId(Long packageWithCourseId) {
		this.packageWithCourseId = packageWithCourseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coursePackageId")
	public Coursepackage getCoursepackage() {
		return this.coursepackage;
	}

	public void setCoursepackage(Coursepackage coursepackage) {
		this.coursepackage = coursepackage;
	}

}
