package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Peopletitle generated by hbm2java
 */
@Entity
@Table(name = "peopletitle", catalog = "ccwchina")
public class Peopletitle implements java.io.Serializable {

	private Integer peopleTitleId;
	private String peopleTitleName;
	private String flag;
	private String avaliable;
	private Set<Userdetail> userdetails = new HashSet<Userdetail>(0);
	private Set<Orderbasic> orderbasics = new HashSet<Orderbasic>(0);

	public Peopletitle() {
	}

	public Peopletitle(String peopleTitleName, String flag, String avaliable,
			Set<Userdetail> userdetails, Set<Orderbasic> orderbasics) {
		this.peopleTitleName = peopleTitleName;
		this.flag = flag;
		this.avaliable = avaliable;
		this.userdetails = userdetails;
		this.orderbasics = orderbasics;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "peopleTitleId", unique = true, nullable = false)
	public Integer getPeopleTitleId() {
		return this.peopleTitleId;
	}

	public void setPeopleTitleId(Integer peopleTitleId) {
		this.peopleTitleId = peopleTitleId;
	}

	@Column(name = "peopleTitleName", length = 45)
	public String getPeopleTitleName() {
		return this.peopleTitleName;
	}

	public void setPeopleTitleName(String peopleTitleName) {
		this.peopleTitleName = peopleTitleName;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "peopletitle")
	public Set<Userdetail> getUserdetails() {
		return this.userdetails;
	}

	public void setUserdetails(Set<Userdetail> userdetails) {
		this.userdetails = userdetails;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "peopletitle")
	public Set<Orderbasic> getOrderbasics() {
		return this.orderbasics;
	}

	public void setOrderbasics(Set<Orderbasic> orderbasics) {
		this.orderbasics = orderbasics;
	}

}
