package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phototrunktype generated by hbm2java
 */
@Entity
@Table(name = "phototrunktype", catalog = "ccwchina")
public class Phototrunktype implements java.io.Serializable {

	private int photoTrunkTypeId;
	private String photoTrunkTypeNameKey;
	private String flag;
	private String avaliable;
	private Set<Photo> photos = new HashSet<Photo>(0);

	public Phototrunktype() {
	}

	public Phototrunktype(int photoTrunkTypeId) {
		this.photoTrunkTypeId = photoTrunkTypeId;
	}

	public Phototrunktype(int photoTrunkTypeId, String photoTrunkTypeNameKey,
			String flag, String avaliable, Set<Photo> photos) {
		this.photoTrunkTypeId = photoTrunkTypeId;
		this.photoTrunkTypeNameKey = photoTrunkTypeNameKey;
		this.flag = flag;
		this.avaliable = avaliable;
		this.photos = photos;
	}

	@Id
	@Column(name = "photoTrunkTypeId", unique = true, nullable = false)
	public int getPhotoTrunkTypeId() {
		return this.photoTrunkTypeId;
	}

	public void setPhotoTrunkTypeId(int photoTrunkTypeId) {
		this.photoTrunkTypeId = photoTrunkTypeId;
	}

	@Column(name = "photoTrunkTypeNameKey", length = 45)
	public String getPhotoTrunkTypeNameKey() {
		return this.photoTrunkTypeNameKey;
	}

	public void setPhotoTrunkTypeNameKey(String photoTrunkTypeNameKey) {
		this.photoTrunkTypeNameKey = photoTrunkTypeNameKey;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "phototrunktype")
	public Set<Photo> getPhotos() {
		return this.photos;
	}

	public void setPhotos(Set<Photo> photos) {
		this.photos = photos;
	}

}
