package com.ccw.bean;

// Generated Aug 28, 2012 11:30:32 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Specialtype generated by hbm2java
 */
@Entity
@Table(name = "specialtype", catalog = "ccwchina")
public class Specialtype implements java.io.Serializable {

	private Integer specialTypeId;
	private String specialTypeName;
	private String picturePath;
	private String flag;
	private String avaliable;
	private Set<Coursecalendar> coursecalendars = new HashSet<Coursecalendar>(0);

	public Specialtype() {
	}

	public Specialtype(String specialTypeName, String picturePath, String flag,
			String avaliable, Set<Coursecalendar> coursecalendars) {
		this.specialTypeName = specialTypeName;
		this.picturePath = picturePath;
		this.flag = flag;
		this.avaliable = avaliable;
		this.coursecalendars = coursecalendars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "specialTypeId", unique = true, nullable = false)
	public Integer getSpecialTypeId() {
		return this.specialTypeId;
	}

	public void setSpecialTypeId(Integer specialTypeId) {
		this.specialTypeId = specialTypeId;
	}

	@Column(name = "specialTypeName", length = 45)
	public String getSpecialTypeName() {
		return this.specialTypeName;
	}

	public void setSpecialTypeName(String specialTypeName) {
		this.specialTypeName = specialTypeName;
	}

	@Column(name = "picturePath", length = 65535)
	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "avaliable", length = 45)
	public String getAvaliable() {
		return this.avaliable;
	}

	public void setAvaliable(String avaliable) {
		this.avaliable = avaliable;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "specialtype")
	public Set<Coursecalendar> getCoursecalendars() {
		return this.coursecalendars;
	}

	public void setCoursecalendars(Set<Coursecalendar> coursecalendars) {
		this.coursecalendars = coursecalendars;
	}

}
